<<<<<<< HEAD
a
b
include
libs
lista_ordenada.txt
Makefile
minishell
obj
readline.supp
srcs
=======
oi
minihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: [Kminihell: 
>>>>>>> bugfix/waitpid
